### ISSUE TITLE
(mongodb)Domain instance embedded properties unexpectedly unupdated

### ISSUE THREAD

**Issue by marsdonne** [grails/grails-data-mapping#1248]
my domain classes:

class Employee {

    static class Contact implements Validateable {
        String zipCode
        String address

        static constraints = {
            zipCode(matches: /[0-9]{6}/)
            address(blank: false)
        }
    }

    String name
    Contact businessContact
    Contact personalContact

    static embedded = ['businessContact', 'personalContact']

    static constraints = {
        name(blank: false)
        businessContact(validator: { it.validate() })
        personalContact(validator: { it.validate() })
    }
}

in example, new domain instance and save it work fine. but, the embedded properties unchanged(in mongo) when you update it.

### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone my example
2. Run with test-app
3. See test-case ‘test update passed, but properties unchanged’ in test-report

### Expected Behaviour

update passed and the properties changed, like insert

### Actual Behaviour

Domain instance embedded properties update passed, but the value unchanged in mongodb

### Environment Information

- **Operating System**: Win10
- **GORM Version:** 6.1.11
- **Grails Version (if using Grails):** 3.3.9
- **JDK Version:** 1.8.0_191

### Example Application

https://github.com/marsdonne/EmbeddProperties

**Comment by marsdonne** [comment]
I solved this problem.  
i found https://stackoverflow.com/questions/53084064/grails-3-1-cant-find-codec-for-domain-class
set in application.yml  `grails.mongodb.engine:` mapping`

Whether this needs to be added to the documentation to make it easier for other users to understand.
