### ISSUE TITLE
Domain class properties inherited from abstract base class are not marked dirty when changed

### ISSUE THREAD

**Issue by timbonicus** [grails/grails-data-mapping#920]
I updated to gorm-hibernate5 6.1.2-SNAPSHOT to pick up @graemerocher's fix for #918 and ran into a different issue.

The attached project has a domain class that inherits from an abstract base class. The abstract base class has a field defined. There's an integration test (InheritedPropertySpecification) that modifies both the inherited field and a field defined in the domain class. Modifying the inherited field does not mark the object as dirty.

This changed in 6.1.0 - if I run the integration test with gorm-hibernate5:6.0.9, the test passes as expected.

I tried changing the abstract base class to a Trait after reading through [grails-core #9678](https://github.com/grails/grails-core/issues/9678), but this gives a PropertyNotFoundException:
```groovy
Caused by: org.hibernate.PropertyNotFoundException: Could not locate field name [name] on class [test.hibernate.Test]
	at org.hibernate.internal.util.ReflectHelper.findField(ReflectHelper.java:356)
	at org.hibernate.property.access.internal.PropertyAccessFieldImpl.<init>(PropertyAccessFieldImpl.java:34)
	at org.hibernate.property.access.internal.PropertyAccessStrategyFieldImpl.buildPropertyAccess(PropertyAccessStrategyFieldImpl.java:26)
	at org.hibernate.mapping.Property.getGetter(Property.java:308)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildPropertyGetter(PojoEntityTuplizer.java:257)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:150)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:60)
	at org.grails.orm.hibernate.proxy.GroovyAwarePojoEntityTuplizer.<init>(GroovyAwarePojoEntityTuplizer.java:35)
	... 81 more
```

The test passes if I add the @Entity annotation to the base class, but in a real application this creates a table for the base class, which is not desired.

### Task List

- [x] Steps to reproduce provided
- [x] ~~Stacktrace (if present)~~ Test provided
- [x] Example that reproduces the problem
- [x] Full description of the issue provided

### Steps to Reproduce

1. Run the InheritedPropertySpecification integration test.
2. Observe the failure on line 31.
3. Switch the commented blocks in build.gradle and gradle.properties to use gorm-hibernate:6.0.9
4. The test passes.

### Environment Information

- **Operating System**: Windows 10
- **GORM Version:** 6.1.2-SNAPSHOT
- **Grails Version (if using Grails):** 3.2.8
- **JDK Version:** 1.8.0_112

### Example Application
[test-hibernate.zip](https://github.com/grails/grails-data-mapping/files/948045/test-hibernate.zip)

**Comment by graemerocher** [comment]
Since this is an abstract class in `src/main/groovy` you have to manually apply dirty checking by adding `@DirtyCheck` fixes the problem:

```groovy
import grails.gorm.dirty.checking.*

@DirtyCheck
abstract class BaseDomainObject {
    String name
}
```

**Comment by timbonicus** [comment]
Thanks @graemerocher! Is this worth mentioning in the GORM upgrade notes? I ask genuinely, I'm not sure how common this pattern is.

Related question - is there any way to explicitly mark a domain class as non-dirty-checkable (to skip dirty check for known unchanging classes)?

**Comment by graemerocher** [comment]
1. Sure pull requests welcome https://github.com/grails/gorm-hibernate5/blob/master/docs/src/docs/asciidoc/introduction/upgradeNotes.adoc
2. No there isn't

**Comment by wkam87** [comment]
Hi, @graemerocher In my project @DirtyCheck doesn't work with groovy traits. Should it?
