### ISSUE TITLE
Multi tenant Schema mode not working for PostgreSQL after fix found in 6.1.5

### ISSUE THREAD

**Issue by andersb** [grails/grails-data-mapping#988]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run gradle integrationTest
2. Test pass
3. Clean database manually
4. Change GORM from 6.1.4 to 6.1.6 in gradle.properties
5. Run gradle integrationTest

### Expected Behaviour

Test should pass

### Actual Behaviour

Exception because query statement is run on wrong schema

This might be related to a fix introduced in 6.1.5 (#956)

Before this fix, the method SchemaHandler.useSchema() wasn't called.
The problem seems now that the medhod SchemaHandler.useDefaultSchema should be called at some point because the test will fail when trying to access a domain that does not implemenet MultiTenant<>.

### Environment Information

- **Operating System**: Windows 10
- **GORM Version:** 6.1.4 - 6.1.6
- **Grails Version (if using Grails):** 3.2.8
- **JDK Version:** 1_8_0_131

### Example Application

[multi-tenancy-demo.zip](https://github.com/grails/grails-data-mapping/files/1234009/multi-tenancy-demo.zip)
